webnavigator/unis/urls.py
from django.urls import path
from . import views

app_name = 'unis'

urlpatterns = [
    path('', views.unis_list, name='list'),
    path('<slug:slug>', views.uni_page, name='page'),
]

webnavigator/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    #path('user-page/', views.user_page_view, name='user-page'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

webnavigator/webnavigator/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('unis/', include('unis.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webnavigator/faculties/models.py
from django.db import models

# Create your models here.

webnavigator/unis/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Uni(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    about = models.TextField()
    wage = models.IntegerField()
    source = models.URLField(null=True)
    slug = models.SlugField()
    img = models.ImageField(default='empty.png', blank=True)
    date = models.DateTimeField(auto_now_add=True)
    scoreBudget = models.FloatField(default=0, validators=[
        MinValueValidator(0),
        MaxValueValidator(100)
    ]) 
    scorePaid = models.FloatField(default=0, validators=[
        MinValueValidator(0),
        MaxValueValidator(100)
    ]) 
    def __str__(self):
        return self.title

webnavigator/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    userScore = models.FloatField(default=0, validators=[
        MinValueValidator(0),
        MaxValueValidator(100)
    ]) 
    def __str__(self):
        return self.user.username
    

webnavigator/users/forms.py
from django import forms

from django.contrib.auth.models import User
from .models import Profile


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    userScore = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-input'})) 
    class Meta: 
        model = Profile
        fields = ['avatar', 'userScore']

webnavigator/faculties/views.py
from django.shortcuts import render

# Create your views here.

webnavigator/unis/views.py
from django.shortcuts import render
from .models import Uni


def unis_list(request):
    unis = Uni.objects.all().order_by('-date')
    return render(request, 'unis/unis_list.html', {'unis': unis})


def uni_page(request, slug):
    uni = Uni.objects.get(slug=slug)
    return render(request, 'unis/uni_page.html', {'uni': uni})

webnavigator/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UpdateUserForm, UpdateProfileForm
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid(): 
            login(request, form.get_user())
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

@login_required
def profile_view(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='/')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})

webnavigator/webnavigator/views.py
from django.shortcuts import render
from unis.models import Uni

def homepage(request):
    unis = Uni.objects.all().order_by('-date')
    return render(request, 'index.html', {'unis': unis})

def about(request):
    return render(request, 'about.html')

webnavigator/templates/about.html
{% extends "layout.html" %}

{% block title %}
    о нас
{% endblock %}

{% block content %}
    <div class="about">
        <div class="container">
            <div class="about-wrapper">
                <p class="about-text">
                    Мы рады приветствовать вас на нашем сайте и надеемся, что с нашей помощью вы осуществите свои мечты. Мы верим в ваш потенциал и готовы поддержать вас на каждом этапе вашего пути.
                    <br>
                    Мы создали эту платформу, чтобы сделать процесс выбора и поступления в ВУЗы проще, удобнее и доступнее для каждого абитуриента.
                    <br>
                    Если у вас есть вопросы или предложения, не стесняйтесь связаться с нами через раздел «Контакты». Вы — наш приоритет!
                    <br>
                    Вместе мы сделаем ваш путь к высшему образованию успешным и увлекательным!
                </p>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <div class="hero">
        <div class="container">
            <div class="hero-wrapper">
                <div class="hero-top">
                    <svg class="hero-img" width="462" height="347" viewBox="0 0 462 347" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g filter="url(#filter0_d_28_132)">
                        <path d="M58.9896 187.673L52.6379 183.792V208.493C52.6379 208.493 43.7455 212.022 43.7455 220.844C43.7455 229.666 48.8269 231.783 48.8269 231.783C48.8269 231.783 42.8109 263.542 42.1576 266.718C41.5043 269.894 37.9616 292.126 37.0762 301.301C36.0163 312.284 35.4883 324.943 35.4883 329.531C35.4883 334.118 52.9555 338 55.8138 338C58.672 338 76.1393 334.824 76.1393 329.531C76.1393 324.238 76.1393 317.886 74.5513 301.301C72.9634 284.715 71.6931 279.422 69.47 266.718C67.2469 254.015 62.1655 231.783 62.1655 231.783C62.1655 231.783 67.5644 229.666 67.5644 220.844C67.5644 212.022 58.9896 208.493 58.9896 208.493V187.673Z" fill="#2478BD" stroke="#2478BD"/>
                        <path d="M360.378 166.148C357.203 152.738 329.89 124.155 234.615 122.391C194.255 121.643 171.415 125.566 155.853 129.801C140.291 134.036 111.074 144.269 104.722 158.737C98.3698 173.205 98.6876 194.731 98.6876 194.731L98.6876 236.724C98.6876 244.134 100.276 248.721 115.837 255.779C131.399 262.837 228.898 269.541 228.898 269.541C228.898 269.541 325.762 264.248 341.641 255.779C357.52 247.31 362.602 247.31 362.602 240.252C362.602 233.195 360.378 166.148 360.378 166.148Z" fill="#2D3E4F" stroke="#2D3E4F"/>
                        <path d="M456.607 141.446L376.893 192.966L373.4 156.973C373.4 156.973 371.176 144.975 351.486 131.918C331.796 118.862 290.827 105.099 226.675 105.099C162.523 105.099 123.46 123.802 110.121 131.918C96.7823 140.034 90.7482 149.915 88.5251 156.973C86.302 164.03 84.714 192.966 84.714 192.966L5 140.034L215.559 8.05752C215.559 8.05752 224.134 1 230.486 1C236.838 1 247 8.05752 247 8.05752L456.607 141.446Z" fill="#2D3E4F" stroke="#2D3E4F"/>
                        <path d="M229.85 221.903C318.457 221.903 346.722 228.96 346.722 239.547C346.722 250.133 266.372 258.249 229.85 258.249C193.329 258.249 112.979 247.663 112.979 239.547C112.979 231.43 141.244 221.903 229.85 221.903Z" fill="#fff" stroke="#DADDD0"/>
                        </g>
                        <defs>
                        <filter id="filter0_d_28_132" x="0.0778809" y="0.5" width="461.455" height="346" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                        <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                        <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
                        <feOffset dy="4"/>
                        <feGaussianBlur stdDeviation="2"/>
                        <feComposite in2="hardAlpha" operator="out"/>
                        <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
                        <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_28_132"/>
                        <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_28_132" result="shape"/>
                        </filter>
                        </defs>
                    </svg>
                    <div>
                        <h1 class="hero-title">
                            твой САЙТ-НАВИГАТОР<br>
                            для поступления в<br>
                            ЛУЧШИЕ ВУЗы страны
                        </h1>
                    </div>
                </div>
                <div class="hero-buttons">
                    <button class="hero-button">выбери специальность</button>
                    <a href="{% url 'unis:list' %}"><button class="hero-button">выбери ВУЗ</button></a>
                </div>
            </div>
        </div>
    </div>
    <div class="best">
        <div class="container">
            <div class="best-wrapper">
                <h2 class="best-title">ТОП ВУЗы:</h2>
                <div class="best-cards">
                    {% for uni in unis %}
                        <div class="best-card">
                            <a href="{% url 'unis:page' slug=uni.slug %}">
                                <img src="{{ uni.img.url }}" alt="{{ uni.title }}">
                            </a>
                            <span class="best-card__name">{{ uni.title }}</span>
                        </div>
                    {% endfor%}
                </div>
            </div>
        </div>
    </div>
    <div class="news">
        <div class="container">
            <div class="news-wrapper">
                <h2 class="news-title">новости</h2>
                <div class="swiper news-slider">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="news-slide">
                                <div class="news-slide__img-wrapper">
                                    <img src="{% static './img/news.png' %}" alt="Новость" class="news-slide__img">
                                </div>
                                <h3 class="news-slide__title">“Мастера на все науки”</h3>
                                <span class="news-slide__text">Сотрудников IT-компаний готовят к преподавательской практике в вузах</span>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="news-slide">
                                <div class="news-slide__img-wrapper">
                                    <img src="{% static './img/news.png' %}" alt="Новость" class="news-slide__img">
                                </div>
                                <h3 class="news-slide__title">“Мастера на все науки”</h3>
                                <span class="news-slide__text">Сотрудников IT-компаний готовят к преподавательской практике в вузах</span>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <div class="news-slide">
                                <div class="news-slide__img-wrapper">
                                    <img src="{% static './img/news.png' %}" alt="Новость" class="news-slide__img">
                                </div>
                                <h3 class="news-slide__title">“Мастера на все науки”</h3>
                                <span class="news-slide__text">Сотрудников IT-компаний готовят к преподавательской практике в вузах</span>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/unis/templates/unis/uni_page.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    {{ uni.title }}
{% endblock %}

{% block content %}
    <div class="unis">
        <div class="container">
            <div class="unis-wrapper">
                <div class="unis-list__item unis-page">
                    <img src="{{ uni.img.url }}" alt="{{ uni.title }}" class="unis-list__item-img">
                    <div class="unis-list__item-right">
                        <h2 >
                            {{ uni.title }}
                        </h2>
                        <p>{{ uni.about }}</p>
                        <p class="unis-list__item-info">
                            {{ uni.body }}
                        </p>
                        {% if uni.scoreBudget != 0 %}
                        <span>Средний балл на бюджет: {{ uni.scoreBudget }}</span><br>
                        {% endif %}
                        {% if uni.scorePaid != 0 %}
                        <span>Средний балл на платное: {{ uni.scorePaid }}</span><br>
                        {% endif %}
                        {% if uni.wage != 0 %}
                        <span>Зарплата: {{ uni.wage }}к+</span><br>
                        {% endif %}
                        <span>Дата обновления: {{ uni.date }}</span><br>
                        <a href="{{ uni.source }}">Источник</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/unis/templates/unis/unis_list.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    ВУЗы
{% endblock %}

{% block content %}
    <div class="unis">
        <div class="container">
            <div class="unis-wrapper">
                <div class="unis-list__item unis-list__item-score">
                    Ожидаемый балл: {% if user.profile.userScore != None %} {{user.profile.userScore}} {% else %} 100 {% endif %}
                </div>
                <div class="unis-list">
                    {% for uni in unis %}
                        {% if user.profile.userScore >= uni.scoreBudget or user.profile.userScore == None %}
                        <div class="unis-list__item">
                            <a href="{% url 'unis:page' slug=uni.slug %}" class="unis-list__item-img--wrapper">
                                <img src="{{ uni.img.url }}" alt="{{ uni.title }}" class="unis-list__item-img">
                            </a>
                            <div class="unis-list__item-right">
                                <h2 >
                                    <a class="unis-list__item-title" href="{% url 'unis:page' slug=uni.slug %}">{{ uni.title }}</a>
                                </h2>
                                <p class="unis-list__item-info">
                                    {{ uni.text }}
                                </p>
                                {% if uni.scoreBudget != 0 %}
                                <span>Средний балл на бюджет: {{ uni.scoreBudget }}</span><br>
                                {% endif %}
                                {% if uni.scorePaid != 0 %}
                                <span>Средний балл на платное: {{ uni.scorePaid }}</span><br>
                                {% endif %}
                                {% if uni.wage != 0 %}
                                <span>Зарплата: {{ uni.wage }}к+</span><br>
                                {% endif %}
                            </div>
                            <a href="{% url 'unis:page' slug=uni.slug %}" class="more">Подробнее</a>
                        </div>
                        {% endif %}
                    {% endfor%}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/users/templates/users/login.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Вход
{% endblock %}

{% block content %}
    <div class="register">
        <div class="container">
            <div class="register-wrapper">
                <div class="unis-list__item">
                    <form action="/users/login/" method="POST" class="register-form">
                        {% csrf_token %}
                        {{ form }}
                        <button class="button-submit">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/users/templates/users/profile.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}

{% block content %}
    <div class="profile">
        <div class="container">
            <div class="profile-wrapper">
                <img class="profile-img" src="{{ user.profile.avatar.url }}"/>
                <div class="unis-list__item unis-page">
                <div class="profile-form-wrapper">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="profile-form">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="small mb-1">Имя:</label>
                                        {{ user_form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1">Сменить аватар:</label>
                                    {{ profile_form.avatar }}
                                </div>
                                <label class="small mb-1">Ожидаемый средний балл:</label> {{ profile_form.userScore }}
                            </div>
                        </div>
                        <button type="submit" class="button">Сохранить</button>
                        <button type="reset" class="button">Сбросить</button>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

webnavigator/users/templates/users/register.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <div class="register">
        <div class="container">
            <div class="register-wrapper">
                <div class="unis-list__item">
                    <form action="/users/register/" method="POST" class="register-form">
                        {% csrf_token %}
                        {{ form }}
                        <button class="button-submit">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}